#!/usr/bin/env python3
"""Builds the portable Windows app (2026-10-10): windows/dist/TeetimeMonitor-<version>-windows-x64.zip.

For people with no Python, no Scoop and no admin rights -- a friend's laptop, or a locked-down
corporate PC. Unzip anywhere (a USB stick works), double-click TeetimeMonitor.cmd. Nothing is
installed, nothing is written outside the unzipped folder: the launcher points the app's
config and data at `userdata\\` next to it (TEETIME_MONITOR_CONFIG_DIR / TEETIME_MONITOR_DATA_DIR,
see src/paths.py), so deleting the folder removes every trace.

The runtime is python.org's own *embeddable* CPython 3.12 (x64): the interpreter and its DLLs
are the ones Python Software Foundation signs, which is what corporate allow-lists tend to
recognise; there is no custom .exe (a freshly built PyInstaller-style executable is exactly
what antivirus products flag). The dependency wheels come from PyPI for win_amd64.

Runs on any OS with `uv` (so the assembly can be checked on a Mac); only the final bytecode
step needs Windows and is skipped elsewhere. Idempotent: the work directory is rebuilt every time.

  python windows/build_portable.py            -> windows/dist/TeetimeMonitor-<v>-windows-x64.zip (+ .sha256)
  python windows/verify_portable.py <zip>     -> checks the result in a clean environment (Windows only)
"""

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tomllib
import urllib.request
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORK = REPO / "windows" / "build-portable"
DIST = REPO / "windows" / "dist"

PYTHON_VERSION = "3.12.10"  # the last 3.12 with Windows binaries (later 3.12.x are source-only)
PYTHON_SERIES = "312"
EMBED_URL = f"https://www.python.org/ftp/python/{PYTHON_VERSION}/python-{PYTHON_VERSION}-embed-amd64.zip"
EMBED_SHA256 = "4acbed6dd1c744b0376e3b1cf57ce906f9dc9e95e68824584c8099a63025a3c3"

TOP = "TeetimeMonitor"  # the folder inside the zip

# The embeddable distribution ignores PYTHON* variables and the working directory when a ._pth
# file sits next to python.exe -- the isolation the Mac launchers get from `python -I`.
PTH = f"""python{PYTHON_SERIES}.zip
.
Lib\\site-packages
import site
"""

RUN_PY = '''"""Entry point of the portable app (generated by windows/build_portable.py)."""
import sys

from src.tui import main

sys.argv[0] = "teetime-monitor"
sys.exit(main())
'''

RUN_WEB_PY = '''"""Entry point of the browser version (generated by windows/build_portable.py)."""
import sys

from src.webui.server import main

sys.argv[0] = "teetime-monitor-web"
sys.exit(main())
'''

# CRLF line endings and no non-ASCII: cmd.exe reads batch files in the OEM code page.
LAUNCHER = r"""@echo off
rem Teetime Monitor, portable. Double-click to start; nothing needs installing.
rem Your settings, logins and tee-time history live in the "userdata" folder next to this file
rem (copy that folder into a newer version's folder to keep them).
setlocal
set "HERE=%~dp0"
set "TEETIME_MONITOR_CONFIG_DIR=%HERE%userdata\config"
set "TEETIME_MONITOR_DATA_DIR=%HERE%userdata\data"
set "PYTHONUTF8=1"
title Teetime Monitor
"%HERE%app\python.exe" "%HERE%app\run.py" %*
set "RC=%errorlevel%"
if not "%RC%"=="0" (
    echo.
    echo Teetime Monitor stopped with an error, code %RC%.
    echo Please send a photo or screenshot of this window to whoever gave you the app.
    pause
)
exit /b %RC%
"""

# The same launcher, starting the browser version (src/webui): a local page in an Edge/Chrome app
# window. The black window stays open while it runs and closes itself when the page is closed.
WEB_LAUNCHER = LAUNCHER.replace("run.py", "run_web.py").replace("title Teetime Monitor", "title Teetime Monitor (browser version)")

README = """TEETIME MONITOR - portable Windows version
==========================================

Nothing to install. You do not need Python, administrator rights or an internet
account other than your own pc caddie login.

START
  1. Unzip this folder anywhere you like (Desktop, Documents, a USB stick).
     If Windows shows a security warning on the zip, right-click the .zip, choose
     Properties, tick "Unblock", press OK - and only then unzip it.
  2. Double-click  TeetimeMonitor.cmd
     A black window opens and the app starts in it. If you have Windows Terminal
     (the modern terminal), it looks nicer there: open it, drag TeetimeMonitor.cmd
     into it and press Enter.
  3. If Windows says "Windows protected your PC", click "More info", then "Run anyway".
     The app is not signed with a paid certificate, so Windows does not know it yet.
  4. Prefer a normal window with buttons instead of the black terminal screen? Double-click
     TeetimeMonitor-Web.cmd instead. It opens the same app in your browser (Edge) and stops by
     itself when you close that window. It listens on this computer only.

KEEP IT / REMOVE IT
  Your settings, logins and history are stored in the "userdata" folder inside this
  folder - nowhere else on the computer. To remove everything, delete the folder.
  To update, unzip the new version and copy your old "userdata" folder into it.
  Your pc caddie password is stored as plain text in userdata\\config\\.env on this
  computer; do not put the folder on a shared drive.

IF SOMETHING GOES WRONG
  Open a Command Prompt in this folder and run   TeetimeMonitor.cmd --doctor
  It checks the setup (network, certificates, login) and prints what is wrong.
  On a company computer, a security product may block programs that run from your
  user folders; then this version cannot run there - the IT department can allow
  the folder, or you can use it on a private computer.

More: https://github.com/ltdan-88/teetime-monitor
"""


def version() -> str:
    with open(REPO / "pyproject.toml", "rb") as handle:
        return tomllib.load(handle)["project"]["version"]


def run(cmd: list[str], **kwargs) -> None:
    print("  $", " ".join(str(part) for part in cmd), flush=True)
    subprocess.run([str(part) for part in cmd], check=True, **kwargs)


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fetch_runtime() -> Path:
    """python.org's embeddable zip, checked against the pinned hash (cached across builds)."""
    cache = WORK.parent / "cache"
    cache.mkdir(parents=True, exist_ok=True)
    target = cache / f"python-{PYTHON_VERSION}-embed-amd64.zip"
    if not target.exists() or sha256_of(target) != EMBED_SHA256:
        print(f"==> downloading {EMBED_URL}")
        with urllib.request.urlopen(EMBED_URL, timeout=120) as response:
            target.write_bytes(response.read())
    if sha256_of(target) != EMBED_SHA256:
        sys.exit(f"error: {target.name} does not match the pinned SHA-256 (got {sha256_of(target)})")
    return target


def write_text(path: Path, text: str, *, crlf: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if crlf:
        text = text.replace("\r\n", "\n").replace("\n", "\r\n")
    path.write_bytes(text.encode("utf-8"))


def requirements() -> Path:
    """The locked dependency set (what CI tests); uv.lock is git-ignored, so resolve one if absent."""
    if not (REPO / "uv.lock").exists():
        print("no uv.lock in this checkout -- resolving one")
        run(["uv", "lock", "--quiet"], cwd=REPO)
    out = WORK / "requirements.txt"
    run(["uv", "export", "--frozen", "--no-dev", "--no-emit-project", "--no-hashes", "--no-header", "--quiet", "-o", out], cwd=REPO)
    if not out.stat().st_size:
        sys.exit("error: uv export produced no requirements")
    return out


def build() -> Path:
    ver = version()
    if WORK.exists():
        shutil.rmtree(WORK)
    stage = WORK / "stage" / TOP
    app = stage / "app"
    site = app / "Lib" / "site-packages"
    app.mkdir(parents=True)
    DIST.mkdir(parents=True, exist_ok=True)
    zip_path = DIST / f"TeetimeMonitor-{ver}-windows-x64.zip"
    for stale in (zip_path, zip_path.with_name(zip_path.name + ".sha256")):
        stale.unlink(missing_ok=True)

    print(f"==> TeetimeMonitor {ver} (Windows x64, portable)")
    print("==> embeddable CPython", PYTHON_VERSION)
    with zipfile.ZipFile(fetch_runtime()) as archive:
        archive.extractall(app)
    write_text(app / f"python{PYTHON_SERIES}._pth", PTH, crlf=True)

    print("==> dependencies (win_amd64 wheels)")
    reqs = requirements()
    target = ["--python-platform", "x86_64-pc-windows-msvc", "--python-version", PYTHON_VERSION[:4], "--target", site]
    run(["uv", "pip", "install", "--no-cache", "--quiet", "--only-binary", ":all:", *target, "-r", reqs])

    print("==> this project")
    src = WORK / "src"
    src.mkdir()
    for name in ("pyproject.toml", "README.md", "LICENSE"):
        shutil.copy2(REPO / name, src / name)
    shutil.copytree(REPO / "src", src / "src", ignore=shutil.ignore_patterns("__pycache__"))
    run(["uv", "pip", "install", "--no-cache", "--quiet", "--no-deps", *target, src])
    for dist in site.glob("*.dist-info"):
        (dist / "direct_url.json").unlink(missing_ok=True)
        record = dist / "RECORD"
        if record.exists():  # the install records must not name the build directory
            lines = [line for line in record.read_text(encoding="utf-8").splitlines() if not line.startswith(f"{dist.name}/direct_url.json,")]
            record.write_text("\n".join(lines) + "\n", encoding="utf-8")
        metadata = dist / "METADATA"
        if dist.name.startswith("teetime_monitor-") and metadata.exists():
            metadata.write_text(metadata.read_text(encoding="utf-8").split("\n\n", 1)[0] + "\n", encoding="utf-8")
    shutil.rmtree(site / "bin", ignore_errors=True)  # POSIX-style console scripts, unused
    for pip_dir in [site / "pip", *site.glob("pip-*.dist-info")]:
        shutil.rmtree(pip_dir, ignore_errors=True)

    write_text(app / "run.py", RUN_PY)
    write_text(app / "run_web.py", RUN_WEB_PY)
    write_text(stage / "TeetimeMonitor.cmd", LAUNCHER, crlf=True)
    write_text(stage / "TeetimeMonitor-Web.cmd", WEB_LAUNCHER, crlf=True)
    write_text(stage / "README.txt", README, crlf=True)

    if sys.platform == "win32":
        # Bytecode at build time: first start is fast, and a read-only folder never matters.
        print("==> bytecode")
        # unchecked-hash: never compared with the source's mtime (a zip round trip keeps only
        # 2-second timestamps); -s/-p: the build directory must not be stored in the file names.
        run([app / "python.exe", "-m", "compileall", "-q", "-f", "-j", "0", "--invalidation-mode", "unchecked-hash",
             "-s", stage, "-p", f"C:\\{TOP}", site])
    else:
        print("==> bytecode skipped (needs Windows; python writes it on the first start)")

    print("==> zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(stage.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(stage.parent).as_posix())
    digest = sha256_of(zip_path)
    zip_path.with_name(zip_path.name + ".sha256").write_text(f"{digest}  {zip_path.name}\n", encoding="utf-8")
    size = zip_path.stat().st_size / 1e6
    print(f"==> {zip_path} ({size:.0f} MB)")
    print(json.dumps({"version": ver, "zip": zip_path.name, "sha256": digest}))
    return zip_path


if __name__ == "__main__":
    os.chdir(REPO)
    build()
