"""Where this app keeps its clubs, credentials and scrape history.

Until 2026-09-17 all three lived in whatever directory you happened to run the tool
from — `./clubs/`, `./data/`, `./.env` — deliberately, and documented that way ("like
`terraform`/`docker-compose`, this reads its own state from whatever directory you run
it in"). That works fine for a terminal tool you always `cd` into.

It stops working the moment a second, non-terminal front end exists. Measured directly
while prototyping a macOS app (see `prototypes/macos-swift/`): an app launched the way
Finder, Launchpad or Spotlight launches it gets **`cwd = /`**, so a double-clicked GUI
would find no clubs, no database and no credentials at all. Any interface that isn't
started from a shell has no meaningful working directory to inherit.

So state moved to one fixed pair of locations that every front end can agree on,
following the XDG split the app already half-used — `global_preferences.py` and
`user_config.py` have written to `~/.config/teetime-monitor/` since 2026-09-08:

    ~/.config/teetime-monitor/          configuration you'd hand-edit or back up
        clubs/<slug>.yaml               saved clubs
        .env                            PCC_USER / PCC_PASS / ANTHROPIC_API_KEY
        preferences.yaml                (already here)
        config                          theme + language (already here)

    ~/.local/share/teetime-monitor/     accumulated data, regenerated by scraping
        <club_id>.db                    one SQLite database per club
        club_directory.json             cached platform club list

Config versus data is the standard XDG line and a real one here: everything in the
first directory is yours and worth backing up, everything in the second is
machine-generated history that only grows.

Both are overridable by environment variable — `TEETIME_MONITOR_CONFIG_DIR` and
`TEETIME_MONITOR_DATA_DIR` — matching the existing `TEETIME_MONITOR_THEME` convention.
That's what makes a throwaway or parallel install possible without touching your real
state, and it's how `scripts/` and any future integration test point the whole app at a
temporary directory in one step instead of patching four separate module constants.

Resolved at import time on purpose: these are process-lifetime facts, and every
consumer re-reads its own module-level constant at call time anyway (see
`club_config.list_clubs()`'s own note on that pattern), so tests keep monkeypatching
those exactly as before.
"""

import os
from pathlib import Path


def _dir_from_env(var: str, default: Path) -> Path:
    """An explicit override wins; otherwise the XDG-style default. `~` is expanded so
    `TEETIME_MONITOR_DATA_DIR=~/somewhere` behaves the way a shell user expects rather
    than creating a literal `./~` directory."""
    raw = os.environ.get(var)
    return Path(raw).expanduser() if raw else default


CONFIG_DIR = _dir_from_env("TEETIME_MONITOR_CONFIG_DIR", Path.home() / ".config" / "teetime-monitor")
DATA_DIR = _dir_from_env("TEETIME_MONITOR_DATA_DIR", Path.home() / ".local" / "share" / "teetime-monitor")

CLUBS_DIR = CONFIG_DIR / "clubs"
ENV_FILE = CONFIG_DIR / ".env"

# The directories this app creates for itself. `.env` and the databases are created by
# whoever writes them; these are the containers they need to land in.
MANAGED_DIRS = (CONFIG_DIR, CLUBS_DIR, DATA_DIR)


def ensure_dirs() -> None:
    """Create the managed directories if they don't exist. Safe to call repeatedly and
    cheap enough to call from any entry point — `mkdir(parents=True, exist_ok=True)` on
    a directory that's already there is a single stat."""
    for directory in MANAGED_DIRS:
        directory.mkdir(parents=True, exist_ok=True)


# --- Migration off the old working-directory layout ---------------------------------

LEGACY_CLUBS_DIR = Path("clubs")
LEGACY_DATA_DIR = Path("data")
LEGACY_ENV_FILE = Path(".env")


def legacy_state_in(directory: Path) -> bool:
    """Does `directory` look like a pre-2026-09-17 install — i.e. does it hold state
    this app would previously have read from there?"""
    return any(
        (directory / legacy).exists()
        for legacy in (LEGACY_CLUBS_DIR, LEGACY_DATA_DIR, LEGACY_ENV_FILE)
    )


def needs_migration(cwd: Path | None = None) -> bool:
    """True when there's old working-directory state to bring across *and* nothing has
    been set up in the new locations yet.

    Deliberately conservative on both halves: it never fires once the new location has
    any clubs in it (so it can't overwrite a real setup), and never fires in a directory
    that has no old state (so an ordinary run from an unrelated directory says nothing).
    """
    cwd = cwd if cwd is not None else Path.cwd()
    already_set_up = CLUBS_DIR.exists() and any(CLUBS_DIR.glob("*.yaml"))
    return not already_set_up and legacy_state_in(cwd)


def migrate_from(cwd: Path | None = None) -> list[str]:
    """Copy a pre-2026-09-17 working-directory layout into the fixed locations.

    **Copies, never moves.** The originals stay exactly where they are, so a migration
    that goes wrong costs nothing and the old directory remains a usable backup. The
    cost is a duplicated database until you delete it yourself, which is the right
    trade for someone's only copy of scrape history that pc caddie itself cannot
    reproduce (see `storage.py`'s module docstring — past tee sheets are gone from the
    site once the day passes).

    Skips anything already present at the destination rather than overwriting, so
    running it twice is safe and a partially-migrated state completes cleanly.
    Returns a human-readable list of what was actually copied.
    """
    import shutil

    cwd = cwd if cwd is not None else Path.cwd()
    ensure_dirs()
    moved: list[str] = []

    for club in sorted((cwd / LEGACY_CLUBS_DIR).glob("*.yaml")) if (cwd / LEGACY_CLUBS_DIR).is_dir() else []:
        if club.name == "club.example.yaml":
            continue  # a template shipped with the repo, not anyone's saved club
        target = CLUBS_DIR / club.name
        if not target.exists():
            shutil.copy2(club, target)
            moved.append(f"club {club.stem}")

    legacy_data = cwd / LEGACY_DATA_DIR
    if legacy_data.is_dir():
        for item in sorted(legacy_data.iterdir()):
            if item.suffix not in {".db", ".json"} or not item.is_file():
                continue  # skip backups, journals, anything not real state
            target = DATA_DIR / item.name
            if not target.exists():
                shutil.copy2(item, target)
                moved.append(f"{item.name} ({item.stat().st_size // 1024} KB)")

    legacy_env = cwd / LEGACY_ENV_FILE
    if legacy_env.is_file() and not ENV_FILE.exists():
        shutil.copy2(legacy_env, ENV_FILE)
        ENV_FILE.chmod(0o600)  # it holds credentials; the old one may have been 644
        moved.append("credentials (.env)")

    return moved
