"""Where this app keeps its clubs, credentials and scrape history.

Until 2026-09-17 all three lived in whatever directory you happened to run the tool
from — `./clubs/`, `./data/`, `./.env` — deliberately, and documented that way ("like
`terraform`/`docker-compose`, this reads its own state from whatever directory you run
it in"). That works fine for a terminal tool you always `cd` into.

It stops working the moment a second, non-terminal front end exists. Measured directly
while prototyping a macOS app (see `macos/`): an app launched the way
Finder, Launchpad or Spotlight launches it gets **`cwd = /`**, so a double-clicked GUI
would find no clubs, no database and no credentials at all. Any interface that isn't
started from a shell has no meaningful working directory to inherit.

So state moved to one fixed pair of locations that every front end can agree on,
following the XDG split the app already half-used — `global_preferences.py` and
`user_config.py` have written to `~/.config/teetime-monitor/` since 2026-09-08:

    ~/.config/teetime-monitor/          configuration you'd hand-edit or back up
        clubs/<slug>.yaml               saved clubs
        .env                            PCC_USER / PCC_PASS / ANTHROPIC_API_KEY
        preferences.yaml                (already here)
        config                          theme + language (already here)

    ~/.local/share/teetime-monitor/     accumulated data, regenerated by scraping
        <club_id>.db                    one SQLite database per club
        club_directory.json             cached platform club list

Config versus data is the standard XDG line and a real one here: everything in the
first directory is yours and worth backing up, everything in the second is
machine-generated history that only grows.

Both are overridable by environment variable — `TEETIME_MONITOR_CONFIG_DIR` and
`TEETIME_MONITOR_DATA_DIR` — matching the existing `TEETIME_MONITOR_THEME` convention.
That's what makes a throwaway or parallel install possible without touching your real
state, and it's how `scripts/` and any future integration test point the whole app at a
temporary directory in one step instead of patching four separate module constants.

Resolved at import time on purpose: these are process-lifetime facts, and every
consumer re-reads its own module-level constant at call time anyway (see
`club_config.list_clubs()`'s own note on that pattern), so tests keep monkeypatching
those exactly as before.
"""

import os
import sys
from pathlib import Path


def _dir_from_env(var: str, default: Path) -> Path:
    """An explicit override wins; otherwise the XDG-style default. `~` is expanded so
    `TEETIME_MONITOR_DATA_DIR=~/somewhere` behaves the way a shell user expects rather
    than creating a literal `./~` directory."""
    raw = os.environ.get(var)
    return Path(raw).expanduser() if raw else default


def _platform_default(windows_var: str, windows_fallback: Path, unix_default: Path) -> Path:
    """Windows keeps config in %APPDATA% (roaming) and data in %LOCALAPPDATA%, the
    per-user locations that need no admin rights; macOS/Linux keep the XDG-style dot
    directories. The variable is read at call time (import time here) so a test can
    set it before reloading the module."""
    if sys.platform == "win32":
        base = os.environ.get(windows_var)
        return (Path(base) if base else windows_fallback) / "teetime-monitor"
    return unix_default


CONFIG_DIR = _dir_from_env(
    "TEETIME_MONITOR_CONFIG_DIR",
    _platform_default("APPDATA", Path.home() / "AppData" / "Roaming", Path.home() / ".config" / "teetime-monitor"),
)
DATA_DIR = _dir_from_env(
    "TEETIME_MONITOR_DATA_DIR",
    _platform_default(
        "LOCALAPPDATA", Path.home() / "AppData" / "Local", Path.home() / ".local" / "share" / "teetime-monitor"
    ),
)

def force_utf8_stdio() -> None:
    """The Windows console defaults to a legacy code page (cp1252) that can't print
    the weather/marker glyphs or every club name; make stdout/stderr UTF-8 so the CLI
    entry points don't crash with UnicodeEncodeError. A no-op elsewhere."""
    if sys.platform != "win32":
        return
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")


CLUBS_DIR = CONFIG_DIR / "clubs"
ENV_FILE = CONFIG_DIR / ".env"

# The directories this app creates for itself. `.env` and the databases are created by
# whoever writes them; these are the containers they need to land in.
MANAGED_DIRS = (CONFIG_DIR, CLUBS_DIR, DATA_DIR)


def ensure_dirs() -> None:
    """Create the managed directories if they don't exist. Safe to call repeatedly and
    cheap enough to call from any entry point — `mkdir(parents=True, exist_ok=True)` on
    a directory that's already there is a single stat."""
    for directory in MANAGED_DIRS:
        directory.mkdir(parents=True, exist_ok=True)


def atomic_write_text(path: Path, text: str, mode: int | None = None) -> None:
    """Replace `path` with `text` all at once: write a temp file beside it, fsync,
    then `os.replace()`. A plain `open("w")` truncates first, so a crash, a full disk
    or a reader in another process (the background scrape, the GUI) could see an
    empty or half-written file -- an empty club YAML loads as `{}` and the club drops
    out of favorites. The GUI already writes these same files atomically.

    `mode` sets the permission bits (0o600 for `.env`); without it an existing file
    keeps its own mode and a new one gets 0o644. Ignored on Windows."""
    import contextlib
    import stat
    import tempfile

    path.parent.mkdir(parents=True, exist_ok=True)
    if mode is None:
        mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    # mkstemp creates the file 0600, so a credentials file is never readable by
    # others even for the moment before the chmod below.
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        if sys.platform != "win32":
            os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp_name)
        raise


# --- Migration off the old working-directory layout ---------------------------------

LEGACY_CLUBS_DIR = Path("clubs")
LEGACY_DATA_DIR = Path("data")
LEGACY_ENV_FILE = Path(".env")


def _migration_marker() -> Path:
    """Written once the old layout is settled (migrated, or the new location found
    already set up). Resolved at call time so tests that patch CONFIG_DIR reach it."""
    return CONFIG_DIR / ".migrated"


def _legacy_clubs(directory: Path) -> list[Path]:
    """Saved-club YAMLs in an old `clubs/` folder: any *.yaml except the repo's
    template that has a top-level `club_id:` key."""
    clubs_dir = directory / LEGACY_CLUBS_DIR
    if not clubs_dir.is_dir():
        return []
    found = []
    for club in sorted(clubs_dir.glob("*.yaml")):
        if club.name == "club.example.yaml" or not club.is_file():
            continue  # a template shipped with the repo, not anyone's saved club
        try:
            text = club.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if any(line.startswith("club_id:") for line in text.splitlines()):
            found.append(club)
    return found


def _is_teetime_db(path: Path) -> bool:
    """A SQLite file with this app's `scrapes` table. Opened read-only (`mode=ro` works
    on a WAL database too: it reads through the -wal/-shm, creating the -shm if needed)."""
    import sqlite3

    try:
        conn = sqlite3.connect(f"{path.resolve().as_uri()}?mode=ro", uri=True)
        try:
            row = conn.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name='scrapes'").fetchone()
        finally:
            conn.close()
    except sqlite3.Error:
        return False
    return row is not None


def _legacy_data_files(directory: Path) -> list[Path]:
    """The old `data/` folder's databases (only ones with a `scrapes` table) and,
    when at least one such database is there, the JSON caches beside them."""
    data_dir = directory / LEGACY_DATA_DIR
    if not data_dir.is_dir():
        return []
    files = sorted(item for item in data_dir.iterdir() if item.is_file())
    databases = [item for item in files if item.suffix == ".db" and _is_teetime_db(item)]
    if not databases:
        return []
    return databases + [item for item in files if item.suffix == ".json"]


def _legacy_env_file(directory: Path) -> Path | None:
    """An old `.env` that holds pc caddie credentials (a PCC_USER/PCC_PASS key)."""
    env = directory / LEGACY_ENV_FILE
    if not env.is_file():
        return None
    try:
        text = env.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    for line in text.splitlines():
        key = line.strip().partition("=")[0].strip().removeprefix("export ").strip()
        if key.startswith(("PCC_USER", "PCC_PASS")):  # `export KEY=` is valid dotenv too
            return env
    return None


def legacy_state_in(directory: Path) -> bool:
    """Does `directory` look like a pre-2026-09-17 install — i.e. does it hold state
    this app would previously have read from there? Checks contents, not just names:
    any web project has a `.env` and a `data/` folder, and copying those in would
    load someone else's secrets into every run."""
    return bool(_legacy_clubs(directory) or _legacy_data_files(directory) or _legacy_env_file(directory))


def needs_migration(cwd: Path | None = None) -> bool:
    """True when there's old working-directory state to bring across *and* nothing has
    been set up in the new locations yet.

    Deliberately conservative on both halves: it never fires once the new location has
    any clubs in it (so it can't overwrite a real setup), and never fires in a directory
    that has no old state (so an ordinary run from an unrelated directory says nothing).
    It also never fires again after a migration: favorites are optional, so "no clubs
    saved" alone would otherwise re-import clubs the user has since removed.
    """
    if _migration_marker().exists():
        return False
    already_set_up = CLUBS_DIR.exists() and any(CLUBS_DIR.glob("*.yaml"))
    if already_set_up:
        _write_migration_marker()
        return False
    cwd = cwd if cwd is not None else Path.cwd()
    return legacy_state_in(cwd)


def _write_migration_marker() -> None:
    try:
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        _migration_marker().write_text("", encoding="utf-8")
    except OSError:
        pass  # only an optimisation; the content checks still apply without it


def migrate_from(cwd: Path | None = None) -> list[str]:
    """Copy a pre-2026-09-17 working-directory layout into the fixed locations.

    **Copies, never moves.** The originals stay exactly where they are, so a migration
    that goes wrong costs nothing and the old directory remains a usable backup. The
    cost is a duplicated database until you delete it yourself, which is the right
    trade for someone's only copy of scrape history that pc caddie itself cannot
    reproduce (see `storage.py`'s module docstring — past tee sheets are gone from the
    site once the day passes).

    Skips anything already present at the destination rather than overwriting, so
    running it twice is safe and a partially-migrated state completes cleanly.
    Returns a human-readable list of what was actually copied.
    """
    import shutil

    cwd = cwd if cwd is not None else Path.cwd()
    ensure_dirs()
    moved: list[str] = []

    for club in _legacy_clubs(cwd):
        target = CLUBS_DIR / club.name
        if not target.exists():
            shutil.copy2(club, target)
            moved.append(f"club {club.stem}")

    # Only .db files with this app's tables (and the JSON caches beside them) --
    # skips backups, journals, and anything that isn't real state.
    for item in _legacy_data_files(cwd):
        target = DATA_DIR / item.name
        if not target.exists():
            if item.suffix == ".db":
                # 2026-10-05: databases run in WAL mode now, so recent commits can sit
                # in `<db>-wal` beside the file; a bare copy would silently drop them.
                # The online backup is a consistent, self-contained copy.
                from .storage import backup_db

                backup_db(item, target)
            else:
                shutil.copy2(item, target)
            moved.append(f"{item.name} ({item.stat().st_size // 1024} KB)")

    legacy_env = _legacy_env_file(cwd)
    if legacy_env is not None and not ENV_FILE.exists():
        shutil.copy2(legacy_env, ENV_FILE)
        if sys.platform != "win32":  # no POSIX permission bits on Windows
            ENV_FILE.chmod(0o600)  # it holds credentials; the old one may have been 644
        moved.append("credentials (.env)")

    _write_migration_marker()
    return moved
